---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tanoshi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      data:
        config.yml: |
          base_url: {{ .baseurl }}
          port: 80
          database_path: /data/tanoshi.db
          create_database: true
          secret: {{ .secret }}
          update_interval: 3600
          auto_download_chapters: false
          plugin_path: /data/plugins
          local_path:
          - name: Manga
            path: /manga/manga
          - name: Hentai
            path: /manga/hentai
          - name: Hentai Nexus
            path: /manga/HentaiNexus/Books
          download_path: /manga/downloads
          cache_path: /cache
          enable_playground: false
          telegram: null
          pushover:
            application_key: {{ .pushovertoken }}
          gotify: null
          myanimelist: null
          anilist:
            client_id: {{ .anilistclientid }}
            client_secret: {{ .anilistclientsecret }}
  data:
    - secretKey: baseurl
      remoteRef:
        key: Tanoshi
        property: baseurl
    - secretKey: secret
      remoteRef:
        key: Tanoshi
        property: secret
    - secretKey: pushovertoken
      remoteRef:
        key: Tanoshi
        property: pushovertoken
    - secretKey: anilistclientid
      remoteRef:
        key: Tanoshi
        property: anilistclientid
    - secretKey: anilistclientsecret
      remoteRef:
        key: Tanoshi
        property: anilistclientsecret
