apiVersion: v1
kind: Service
metadata:
  name: miniflux-postgres
  labels:
    app: miniflux
    name: postgres
    role: primary
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgres-port
  type: ClusterIP
  selector:
    app: miniflux
    name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-postgres-headless
  labels:
    app: miniflux
    name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgres-port
  clusterIP: None
  selector:
    app: miniflux
    name: postgres
