apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels: &labels
    app.kubernetes.io/part-of: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      runtimeClassName: nvidia
      volumes:
        - name: media
          hostPath:
            path: /mnt/storage/media
            type: Directory
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: transcodes
          emptyDir:
            sizeLimit: 1Gi
            medium: Memory
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.8.13
          imagePullPolicy: Always
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: jellyfin.fadhlika.com
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 60
          volumeMounts:
            - name: media
              mountPath: /data
            - name: config
              mountPath: /config
            - name: transcodes
              mountPath: /transcodes
          resources:
            limits:
              nvidia.com/gpu.shared: 1 # requesting 1 GPU
