apiVersion: v1
kind: Service
metadata:
  name: jellyfin-tcp
  labels:
    app.kubernetes.io/part-of: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.205
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  selector:
    app.kubernetes.io/part-of: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: server
  ports:
    - protocol: TCP
      port: 8096
      targetPort: http
      name: http
