apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/part-of: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: server
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/part-of: jellyfin
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/component: server
  ports:
    - protocol: TCP
      port: 8096
      targetPort: http
      name: http
