---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: microbin-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: username
          remoteRef:
              key: MicroBin
              property: username
        - secretKey: password
          remoteRef:
              key: MicroBin
              property: password
        - secretKey: uploaderpassword
          remoteRef:
              key: MicroBin
              property: uploaderpassword
