---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
      interval: 30m
  values:
    fullnameOverride: k8s-gateway
    ttl: 1
    service:
      type: LoadBalancer
      loadBalancerClass: metallb
      annotations:
        metallb.universe.tf/loadBalancerIPs: '192.168.2.201'
      externalTrafficPolicy: Local
      port: 53
    domain: fadhlika.com
    replicaCount: 1
