apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  labels: &labels
    app.kubernetes.io/part-of: miniflux
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      containers:
        - name: miniflux-migration
          image: miniflux/miniflux:2.0.50
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: miniflux-postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: miniflux-postgres-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-postgres-secret
                  key: db_password
            - name: DATABASE_URL
              value: 'postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_USER)?sslmode=disable'
            - name: RUN_MIGRATIONS
              value: '1'
            - name: CREATE_ADMIN
              value: '1'
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: miniflux-secret
                  key: admin_username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: miniflux-secret
                  key: admin_password
            - name: BASE_URL
              value: https://miniflux.fadhlika.com
          livenessProbe:
            exec:
              command: ['/usr/bin/miniflux', '-healthcheck', 'auto']
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
