---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: miniflux-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: admin_username
          remoteRef:
              key: Miniflux
              property: username
        - secretKey: admin_password
          remoteRef:
              key: Miniflux
              property: password
