apiVersion: v1
kind: Service
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/part-of: miniflux
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: miniflux
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
