---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: szurubooru-postgres-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  data:
    - secretKey: db_user
      remoteRef:
        key: Szurubooru
        property: dbuser
    - secretKey: db_password
      remoteRef:
        key: Szurubooru
        property: dbpassword
