apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels: &labels
    app.kubernetes.io/part-of: flaresolverr
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8191
              name: http
          env:
            - name: TZ
              value: Asia/Jakarta
