apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels:
    app.kubernetes.io/part-of: flaresolverr
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: flaresolverr
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/component: server
  ports:
    - name: http
      protocol: TCP
      port: 8191
      targetPort: http
