apiVersion: v1
kind: Secret
metadata:
    name: op-credentials
type: Opaque
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:Y4undJ+WWDvdfof8dpH3heBUiv36w3p1upHlyAqhQsB+2RZEa3Jltc5/AROmENcA6F7n5Mv3f1TXa0I6Z5P28I4oihxJ+kPxvjtVV2qcW5CbC7KwbSPpM2oRXD9bNAa8qhxB085dOSZh5b2lxlABgbVqTTVU5lmqBxkfHLCQNJPnPm6RmzqdgfTJ8IecZzDL2G4fk9gy6d2JZ+YGE4ttVFWFlCszk+d2iNPOWFb/gWZmmG6DcMThQ0pyu7iAJTxkrjPcxKrelFRAGVYV1X3EnL4hy0emvxaVU/YVESvklJo9uTYlZkQEogggadV3tE4HQ6hShnaRXO/qmDskGKC+MQ6afVala8kYqKt9FpGi6jLqLAD/4uDgnLxnyy//lR39xuhVeKWcfcdrIoFR11qHxgykbWcUYJ13lsiVLxZ7yqyZC6myI/MG4sDso1st8EdOOYdbESj8Jc/RYEonkHAmZlaO/guogilnr+BPmuPuCxXJtZvA3yxD4OCwiSuVvAeXdCWhczbhEP98a2UooWpAGV4s1RQcRSd4mpQs+YrzjCbsa1O5WMYS8dq1zP7jXlYQMvl4Fba6OFnTk+O7pS0rFwPNmAFrU6puFJJiEkqpe44TXzE0HbhQUNhozhZxqPos1u8IVqwmR6U2365OULWxzGcZc9iG3bZ9eJZNEQeq3F7FmQa2tVszV2Tys9RbIZzvL5X9pvQcRryajW47nlerXHXQpxOi3pHcql0w+rhkhODkmw7oSR4PHERSTh4S5AMMWltLD9y0vq0icpNZdnVcsCEEOU0K9UuLmbmg8HdhRYG//JFGesjFasL5jQt5DrpDf9TMwjscp0omFh3ijYYoIcFNWUr5PfyQ0bK7c36E8VKvz0WsWMCBQup9XQqCOOe+birMQIztV2S0a2dVLay4SDJPCpHRk9WruHu2lFsWTJFH4gsGmbBIzx0VWA/cnEmVbjzQrlfvS1Ryw+TeCnbxgqgEODcUDGobCFFOWcIsDY0G19TrcbneHHnCd4alF9msOv82k3ETOWYhyDWJ0SAWthSViiljRn0nHOs+0MZLka5cQ53jLAuyRSDQBhhne3fYNmIS1zfMCvTfnLp+YbHuoojr1t+Z1Baly1DCW9VEy2NMWCAjT4lCXGb9jDw/3wJIlAlW5eXEQG5Fj55ScozpjlozMVmyZ+NSvjTaByilT+CNQ+wqt68MQ4tmPNLJB7ojXZK6fa/duQ4muEDFC2QInriIxiS8OHX2CWMSGzxBKGYsHR2VqVHSyVQOehkFdqy7r+3ValZshYYJ5S6QshJ7bpBm3pDqTj/G6tVHC1roHZt0DjQUlN4TlXxZ5bNC84BuThLs4mCQW6CJd4eWp3Ju1xys5QWwS3DB6blPFk+xCrEFTLWsLguKCtdfFlC0oAzW2FqgWPrgoAN2FHXaxos3lqAiKNhIdk25vguib7kM1NRW9LyMnnXJTmz59EthMIo8N8gVU8CBlCWf6S1U0op6xsFrP9IG9LPIcgJqj7+1KInVYaDrkQ9/2QJx6QmEiqZMsFoK0EdML8imqk85pmPkPQizFFwc19B2xfJkcTB0XH/CyybFWKxSrHCZnYybiM8Ng72vyrFtDBim7QqimuhBtMTY7cTKK3CJ1jrv8O5CKMsVt9LKiSy66R7ZDmdeL1M49K0rGh1FaWT+lvyCA5r6DPiwVSxaPxy/uwSsTYIQcw8o4ojxmInUY/sJEVYrze160KI5ZBvx5TYYO5iW8CxZvHJo6w9G9j8or3PZCDbfxN8G8QxbzHX6T9YQF6EW5fOTTFhFGt8zuY5QelOGyLyFVSuNlcepBAAjTwZYbVSxdkOuga32CMP3XPg0HVOc6cIHDAZjrcfdeJ89YGq/gTyNK082bn52bD+F7KRypsQV71Tk2xDVCrn1hbHoCfU/54ekW0BEyjwezFeC5pGR,iv:s40igJXfg5W3bib6C3tSDfHs9gWau2Yg+4LjRZc5zPw=,tag:C8RFJOZYDAch2n16tYOoFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rywm2s9s24hma5q3rvnn3tl8ys5ccajwhyyv696j25secg43657suarrph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZlAvU3JKV1pwSjcrMExK
            QmN2dGdUQWV3bndJVXpXVk1RcjI5YjVRcVNZCkJuUmVwbVl3MElTTHJoT3h6RmdQ
            ZE5tN0hiMDZLTTBRT2t1bzcxTmUxaU0KLS0tIERXYUNxOVA3eGFtU2NNSWYwa0d6
            YUtSeFdmUklNSWtSdGZlcTgxR2NNOTgKQpP0bDoQpzawYw7lunIlcZhKpgl0b1q+
            jfcVF9lxrdU62qhmK18YNlys9WT1ulID9u6u8U61QyJj6iWqGb8XgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-05T09:13:24Z"
    mac: ENC[AES256_GCM,data:fQKCqLmGBfJMiMLbchyGps4aFkKE4a6RQCeO2jXGnnCBo4sn85UAbh8VFBc9Pkxo4iUhBapzI9AHsx4efTPSRzQsWYvz5AZ+J+IQ0YiZzCFhPcbJs/VhOuBwdYmS+IsPfEIF/Ro4fACWz6lLWF/AAmUm0Hz11Mram1JT1bEu4ig=,iv:H/X+J0Vlw7y2Y29IpPP54a1OGrqYzrRUjr91dn+2jWQ=,tag:Fa5ZnKmQtqhvn86ITrX1qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
