---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  dependsOn:
    - name: repositories
  wait: true
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  path: ./kubernetes/core
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
