apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakamata
  labels: &labels
    app.kubernetes.io/part-of: sakamata
    app.kubernetes.io/name: sakamata
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      containers:
        - name: sakamata
          image: ghcr.io/mfadhlika/sakamata:main
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: sakamata-postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sakamata-postgres-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sakamata-postgres-secret
                  key: db_password
            - name: DATABASE_URL
              value: 'postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_USER)?sslmode=disable'
            - name: LISTEN_ADDR
              value: '0.0.0.0'
            - name: PORT
              value: '8080'
            - name: BASE_URL
              value: https://sakamata.fadhlika.com
          ports:
            - containerPort: 8080
              name: http
