---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gha-runner-scale-set
  namespace: flux-system
spec:
  path: ./kubernetes/apps/arc-system/gha-runner-scale-set/app
  dependsOn:
    - name: gha-runner-scale-set-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
