---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag":"{{ .accounttag }}",
            "TunnelSecret":"{{ .tunnelsecret }}",
            "TunnelID":"{{ .tunnelid }}"
          }
  data:
    - secretKey: accounttag
      remoteRef:
        key: Cloudflare
        property: accounttag
    - secretKey: tunnelsecret
      remoteRef:
        key: Cloudflare
        property: tunnelsecret
    - secretKey: tunnelid
      remoteRef:
        key: Cloudflare
        property: tunnelid
