---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: cloudflare-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: cloudflare_api_token
          remoteRef:
              key: Cloudflare
              property: token
        - secretKey: cloudflare_api_key
          remoteRef:
              key: Cloudflare
              property: key
