apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vaultwarden-secret
stringData:
    db_user: vaultwarden
    db_password: fzkY5WUWo7GNCj
    db_url: postgresql://vaultwarden:fzkY5WUWo7GNCj@vaultwarden-postgres:5432/vaultwarden
