---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@fadhlika.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@fadhlika.com
            apiKeySecretRef:
              name: cloudflare-secret
              key: cloudflare_api_key
        selector:
          dnsZones:
            - fadhlika.com
