---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  values: {}
