---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      backupTarget: nfs://openmediavault.oyoy.lan:/storage/backups/longhorn
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      host: longhorn.fadhlika.com
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        kubernetes.io/ingress.class: "traefik"
        external-dns/is-public: "true"
