---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: longhorn-backup-credentials
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: AWS_ENDPOINTS
          remoteRef:
              key: OCI Bucket
              property: endpoint
        - secretKey: AWS_ACCESS_KEY_ID
          remoteRef:
              key: OCI Bucket
              property: accesskey
        - secretKey: AWS_SECRET_ACCESS_KEY
          remoteRef:
              key: OCI Bucket
              property: secretkey
