---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: valheim-server-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: servername
          remoteRef:
              key: Valheim Server
              property: servername
        - secretKey: serverpass
          remoteRef:
              key: Valheim Server
              property: serverpass
        - secretKey: worldname
          remoteRef:
              key: Valheim Server
              property: worldname
