apiVersion: v1
kind: Service
metadata:
  name: valheim-server
  annotations:
    metallb.universe.tf/allow-shared-ip: "valheim-server"
  labels:
    app.kubernetes.io/instance: valheim-server
    app.kubernetes.io/name: valheim-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.203
  selector:
    app.kubernetes.io/instance: valheim-server
    app.kubernetes.io/name: valheim-server
  ports:
    - protocol: UDP
      port: 2456
      targetPort: game
      name: game
    - protocol: UDP
      port: 2457
      targetPort: query
      name: query
