apiVersion: v1
kind: Service
metadata:
  name: valheim-server
  labels:
    app.kubernetes.io/part-of: valheim-server
    app.kubernetes.io/name: valheim-server
    app.kubernetes.io/component: server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.203
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  selector:
    app.kubernetes.io/part-of: valheim-server
    app.kubernetes.io/name: valheim-server
    app.kubernetes.io/component: server
  ports:
    - protocol: UDP
      port: 2456
      targetPort: game
      name: game
    - protocol: UDP
      port: 2457
      targetPort: query
      name: query
