apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydrus-network-client
  labels: &labels
    app.kubernetes.io/part-of: hydrus-network
    app.kubernetes.io/name: hydrus-network-client
    app.kubernetes.io/component: client
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hydrus-network-client-data
      containers:
        - name: hydrus-network-client
          image: ghcr.io/hydrusnetwork/hydrus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5800
              protocol: TCP
              name: novnc
            - containerPort: 5900
              protocol: TCP
              name: vnc
            - containerPort: 45868
              protocol: TCP
              name: booru
            - containerPort: 45869
              protocol: TCP
              name: api
          volumeMounts:
            - name: data
              mountPath: /opt/hydrus/db
