apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: frp-operator
spec:
  interval: 30m
  url: https://github.com/mfadhlika/frp-operator
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
