apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: immich
spec:
  interval: 1m
  url: https://github.com/immich-app/immich-charts
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
