---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-gateway
spec:
  interval: 30m
  url: https://github.com/mfadhlika/k8s_gateway
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/k8s-gateway
