apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
spec:
  interval: 1m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.26
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/chart/
