apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  labels: &labels
    app.kubernetes.io/part-of: linkding
    app.kubernetes.io/name: linkding
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-data
      containers:
        - name: linkding
          image: sissbruecker/linkding:latest
          imagePullPolicy: Always
          env:
            - name: LD_LOG_X_FORWARDED_FOR
              value: 'true'
            - name: LD_DB_ENGINE
              value: postgres
            - name: LD_DB_HOST
              value: linkding-postgres
            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkding-postgres-secret
                  key: db_user
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-postgres-secret
                  key: db_password
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: username
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /etc/linkding/data
          ports:
            - containerPort: 9090
              name: http
