apiVersion: v1
kind: Service
metadata:
  name: devbox
  labels:
    kubevirt.io/os: linux
    kubevirt.io/domain: devbox
    app.kubernetes.io/part-of: devbox
    app.kubernetes.io/name: devbox
  annotations:
    coredns.io/hostname: devbox.fadhlika.com
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  externalTrafficPolicy: Cluster
  selector:
    kubevirt.io/os: linux
    kubevirt.io/domain: devbox
    app.kubernetes.io/part-of: devbox
    app.kubernetes.io/name: devbox
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
