apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nitter-redis
  labels: &labels
    app.kubernetes.io/part-of: nitter
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
spec:
  serviceName: nitter-redis
  replicas: 1
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nitter-redis-data
      containers:
        - name: redis
          image: redis:6-alpine
          ports:
            - containerPort: 6379
              name: redis-port
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
