---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapscheduler
spec:
  interval: 30m
  chart:
    spec:
      chart: snapscheduler
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  values: {}
