---
apiVersion: v1
kind: Service
metadata:
  name: szurubooru-postgres
  labels:
    app.kubernetes.io/part-of: szurubooru
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgres-port
  clusterIP: None
  selector:
    app.kubernetes.io/part-of: szurubooru
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
