---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: nitter-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    target:
        template:
            engineVersion: v2
            data:
                nitter.conf: |
                    [Server]
                    hostname = "nitter.fadhlika.com" 
                    title = "nitter"
                    address = "0.0.0.0"
                    port = 8080
                    https = false   
                    httpMaxConnections = 100
                    staticDir = "./public"

                    [Cache]
                    listMinutes = 240 
                    rssMinutes = 10 
                    redisHost = "nitter-redis" 
                    redisPort = 6379
                    redisPassword = ""
                    redisConnections = 20 
                    redisMaxConnections = 30

                    [Config]
                    hmacKey = "{{ .secret }}" 
                    base64Media = false
                    enableRSS = true 
                    enableDebug = false
                    proxy = "" 
                    proxyAuth = ""
                    tokenCount = 10

                    [Preferences]
                    theme = "Nitter"
                    replaceTwitter = "nitter.fadhlika.com"
                    replaceYouTube = "piped.video"
                    replaceReddit = "teddit.net"
                    proxyVideos = true
                    hlsPlayback = true
                    muteVideos = true
                    infiniteScroll = false
    data:
        - secretKey: secret
          remoteRef:
              key: Nitter
              property: secret
