apiVersion: apps/v1
kind: Deployment
metadata:
  name: stash
  labels: &labels
    app.kubernetes.io/part-of: stash
    app.kubernetes.io/name: stash
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      runtimeClassName: nvidia
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: stash-config
        - name: data
          persistentVolumeClaim:
            claimName: stash-data
        - name: storage
          hostPath:
            path: /mnt/storage
            type: Directory
      containers:
        - name: stash
          image: stashapp/stash:latest
          imagePullPolicy: Always
          env:
            - name: STASH_STASH
              value: /stash
            - name: STASH_GENERATED
              value: /data/generated/
            - name: STASH_METADATA
              value: /data/metadata/
            - name: STASH_CACHE
              value: /data/cache/
            - name: STASH_PORT
              value: '9999'
            - name: STASH_EXTERNAL_HOST
              value: https://stash.fadhlika.com
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          ports:
            - containerPort: 9999
              protocol: TCP
              name: http
          volumeMounts:
            - name: storage
              mountPath: /stash
              subPath: stash
            - name: data
              mountPath: /data
            - name: config
              mountPath: /root/.stash
          resources:
            limits:
              nvidia.com/gpu.shared: 1 # requesting 1 GPU
              memory: '4Gi'
              cpu: '4'
