apiVersion: apps/v1
kind: Deployment
metadata:
  name: stash
  labels:
    app.kubernetes.io/instance: stash
    app.kubernetes.io/name: stash
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: stash
      app.kubernetes.io/name: stash
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: stash
        app.kubernetes.io/name: stash
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      runtimeClassName: nvidia
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: stash-config
        - name: storage
          nfs:
            server: openmediavault.oyoy.lan
            path: /storage
      containers:
        - name: stash
          image: stashapp/stash:latest
          imagePullPolicy: Always
          env:
            - name: STASH_STASH
              value: /stash
            - name: STASH_GENERATED
              value: /data/generated/
            - name: STASH_METADATA
              value: /data/metadata/
            - name: STASH_CACHE
              value: /data/cache/
            - name: STASH_PORT
              value: "9999"
            - name: STASH_EXTERNAL_HOST
              value: https://stash.fadhlika.com
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          ports:
            - containerPort: 9999
              protocol: TCP
              name: http
          volumeMounts:
            - name: storage
              mountPath: /stash
              subPath: stash
            - name: storage
              mountPath: /data
              subPath: apps/stash
            - name: config
              mountPath: /root/.stash
          resources:
            limits:
              nvidia.com/gpu.shared: 1 # requesting 1 GPU
