apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sakamata-postgres-secret
stringData:
    db_user: ENC[AES256_GCM,data:eZw9ovvAlMI=,iv:u7HDc9VgMFgu68oolpiHPlHq7KfvaNjZo+tdfwrCnMA=,tag:3lBpabcLRrEBEIvlMdMrCw==,type:str]
    db_password: ENC[AES256_GCM,data:/R9NYrG+GNI=,iv:mVXeZsfOoakPTJfDwnqUO2BDu9wWHwXA6oKBTu4ts0M=,tag:cAqHx0qnpU6GhT4YRWBVfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rywm2s9s24hma5q3rvnn3tl8ys5ccajwhyyv696j25secg43657suarrph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK2VYWGhwQTROeVF6c2VK
            ZEJIOHlXUUNxcWhmY2MwT3ZXdG1OS0NHVVNvCjdNVUxhNDhvbWFzNE5IZlhUN0RM
            YjFEZmJEWWJHL1VDTGRqaUNrUlNZSGsKLS0tIFdla20ydGx5YlFhOHBkbjhxQ1JV
            bHppcUwrNGl2UG45YjAySmxFeXc0MjQK93ksg2OGCCHF08rHsSbFeYwSgdCCx81e
            5Y+4X4vC0amZeiVTb4MZSaBG0G3meTZxQpaAxprnYNR4Iu85Iyw77g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-08T13:12:50Z"
    mac: ENC[AES256_GCM,data:VQthFcwzF6sP4s5pzKAsH5Lk3FtHRprum4LpOPnbm1Z17rI1c3KAPH7+hrYNFaC/UspfQ6qVZbMOZkELDSZue6n9y/AqQAhJiwWgz79xP2gloJKv2yWBq9wlOAbuLc6+fx/HLI3OYZaB3JOIOj8HocXixSzA2W/Y7oMUnM+HvjE=,iv:EhUdeu0TyjT2PslGcC5vctnBCsVjlFcjpOxm7FGWuq8=,tag:sSM+4hLpUMwW9QvrYz3oKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
