apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sakamata-postgres
  labels: &labels
    app.kubernetes.io/part-of: sakamata
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  serviceName: sakamata-postgres
  replicas: 1
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sakamata-postgres-data
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres-port
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sakamata-postgres-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sakamata-postgres-secret
                  key: db_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            exec:
              command: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
