apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3
  labels: &labels
    app.kubernetes.io/part-of: iperf3
    app.kubernetes.io/name: iperf3
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: iperf3
          image: networkstatic/iperf3:latest
          imagePullPolicy: Always
          command:
            - 'iperf3'
            - '-s'
          ports:
            - containerPort: 5201
              name: tcp
              protocol: TCP
            - containerPort: 5201
              name: udp
              protocol: UDP
