apiVersion: v1
kind: Service
metadata:
  name: iperf3-tcp
  labels:
    app.kubernetes.io/part-of: iperf3
    app.kubernetes.io/name: iperf3
    app.kubernetes.io/component: server
  annotations:
    metallb.universe.tf/allow-shared-ip: 'iperf3'
    metallb.universe.tf/loadBalancerIPs: 192.168.2.211
    coredns.io/hostname: iperf3.fadhlika.com
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  selector:
    app.kubernetes.io/part-of: iperf3
    app.kubernetes.io/name: iperf3
    app.kubernetes.io/component: server
  ports:
    - protocol: TCP
      port: 5201
      targetPort: tcp
      name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-udp
  labels:
    app.kubernetes.io/part-of: iperf3
    app.kubernetes.io/name: iperf3
    app.kubernetes.io/component: server
  annotations:
    metallb.universe.tf/allow-shared-ip: 'iperf3'
    metallb.universe.tf/loadBalancerIPs: 192.168.2.211
    coredns.io/hostname: iperf3.fadhlika.com
spec:
  type: LoadBalancer
  loadBalancerClass: metallb
  selector:
    app.kubernetes.io/part-of: iperf3
    app.kubernetes.io/name: iperf3
    app.kubernetes.io/component: server
  ports:
    - protocol: UDP
      port: 5201
      targetPort: udp
      name: udp
