---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 30m
  # https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml
  values:
    logLevel: debug
    sources:
      - crd
      - service
      - ingress
    extraArgs:
      - '--ingress-class=frp'
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: cloudflare_api_token
    policy: sync
    txtPrefix: 'k8s.'
    crd:
      # disabled, pulled from source repo in crds/
      create: false
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 100Mi
