---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: 25.21.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: false

    kube-state-metrics:
      enabled: false

    prometheus-node-exporter:
      enabled: false

    prometheus-pushgateway:
      enabled: false

    serverFiles:
      prometheus.yml:
        scrape_configs:
          - job_name: OpenWrt
            static_configs:
              - targets:
                  - 'oyoy.oyoy.lan:9100'
                  - 'badifadi.badifadi.lan:9100'
