---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  path: ./kubernetes/core/cloudflare-operator-system/cloudflare-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator-clustertunnel
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: cloudflare-operator
  path: ./kubernetes/core/cloudflare-operator-system/cloudflare-operator/clustertunnel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
