---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: espial
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/espial/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 5m
  timeout: 15m
