apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actual/ks.yaml
  - changedetection/ks.yaml
  - jellyfin/ks.yaml
  - memos/ks.yaml
  - miniflux/ks.yaml
  - node-red/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - stash/ks.yaml
  - szurubooru/ks.yaml
  - tanoshi/ks.yaml
  - transmission/ks.yaml
  - tvheadend/ks.yaml
  - valheim-server/ks.yaml
