---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: szurubooru-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      engineVersion: v2
      data:
        config.yaml: |
          name: Szurubooru
          domain: {{ .baseurl }}
          secret: {{ .secret }}
          user_agent: szurubooru/2.5
          max_dl_filesize: 100.0E+6
          debug: 0
          show_sql: 0
          data_url: /data/
          data_dir: /data
          database: postgres://{{ .db_user }}:{{ .db_password }}@szurubooru-postgres:5432/szurubooru
  data:
    - secretKey: baseurl
      remoteRef:
        key: Szurubooru
        property: baseurl
    - secretKey: secret
      remoteRef:
        key: Szurubooru
        property: secret
    - secretKey: db_user
      remoteRef:
        key: Szurubooru
        property: dbuser
    - secretKey: db_password
      remoteRef:
        key: Szurubooru
        property: dbpassword
