---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: coder-postgres-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    target:
        template:
            engineVersion: v2
            data:
                db_url: postgres://{{ .db_user }}:{{ .db_password }}@coder-postgres:5432/{{ .db_user }}?sslmode=disable
    data:
        - secretKey: db_user
          remoteRef:
              key: Coder
              property: dbuser
        - secretKey: db_password
          remoteRef:
              key: Coder
              property: dbpassword
