---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.2.208
        externalTrafficPolicy: Local
        loadBalancerClass: metallb
        type: LoadBalancer
