---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frp-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
  data:
    - secretKey: auth_token
      remoteRef:
        key: frp
        property: password
