apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - service-account.yaml
  - service-db.yaml
  - service.yaml
  - sts-postgresql.yaml
