apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: immich-postgresql
data:
    password: ENC[AES256_GCM,data:dN0Byhw4GzY=,iv:JHlR9wVLTUBaDXgKnH0oB/3kXOvTU/eNl7hekZNPRg4=,tag:Tij8UpWUMbLS2YIl/5q/zQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:oFy2R4CD/4U=,iv:RIDOZz+T0a8ZxB9fQPmkzfJqbWTqMOth3z1zLiK+Zzo=,tag:e3h7yvXfN5Waz60f8uE1Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rywm2s9s24hma5q3rvnn3tl8ys5ccajwhyyv696j25secg43657suarrph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUmRWMlVhZXdoWGRCeHVH
            OVhXa0dLZ2ZZMjE4cS80eXpHTy9LZ1Q1czN3CmNubU5RTGU4anhWckF4UmNUaDVO
            QjNFajdJYWlkRUVNQzlwVVUxbG9hV3MKLS0tIDRMQWVHRGFJaWhmVkxSTytEWDVX
            OE83a3hFcVZGcHlUM3ZUdUlsWUlHamMK2MycADzLBFLxvtKX2Be9WKkuqinP0924
            JTyBE3RAwCLdMcD3uRV5R/4NcAW2dOjK8k+pXCdyDftfdw1dW2RZyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-05T09:11:57Z"
    mac: ENC[AES256_GCM,data:oRezrR7M6hRPB8RSy4tIAMpY6tKBfSElKawwk1o+AYz1W+11zjBfXlgP9bwXXzOOdu+EEVgPKxI049S5Tk4u59VHindNHNYaIYaYVcgsX4nA10MWjz9p8C1U0fp29yu89gMbGxf3am0FFOHJyEJWPLIC87JtDMAnEuC/p+J9MhY=,iv:xBv3qURekZIsBkiv5DndvA7nghlJVnAf4/v9NytC6Vc=,tag:GdDpv7iKYoIsG9cvc5nhig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
