---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnels-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflare-tunnels-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnels-operator-clustertunnel
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/cloudflare-tunnels-operator/clustertunnel
  dependsOn:
    - name: cloudflare-tunnels-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
