---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
          secretKeyRef:
            name: coder-postgres-secret
            key: db_url
        - name: CODER_ACCESS_URL
          value: "https://coder.fadhlika.com"
      ingress:
        enable: true
        host: coder.fadhlika.com
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
          kubernetes.io/ingress.class: "traefik"
          external-dns/is-public: "true"
        tls:
          enable: true
