apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  labels:
    app.kubernetes.io/instance: node-red
    app.kubernetes.io/name: node-red
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-red
      app.kubernetes.io/name: node-red
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: node-red
        app.kubernetes.io/name: node-red
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: node-red-data
        - name: config
          configMap:
            name: node-red-config
      initContainers:
        - name: init
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "chown -R 1000:1000 /data"
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: node-red
          image: nodered/node-red:3.1
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Jakarta
            - name: OS_CREDENTIAL_PATH
              value: /config/oci_config
          ports:
            - containerPort: 1880
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/settings.js
              subPath: settings.js
              readOnly: true
