apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-plugin-configs
data:
  default: |-
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: true
        resources:
          - name: nvidia.com/gpu
            replicas: 8
