---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
  values:
    config:
      name: nvidia-plugin-configs
      default: default
    gfd:
      enabled: true
    migStrategy: "none"
    failOnInitError: true
    nvidiaDriverRoot: "/"
    runtimeClassName: nvidia
