apiVersion: v1
kind: Service
metadata:
  name: tvheadend
  labels:
    app.kubernetes.io/part-of: tvheadend
    app.kubernetes.io/name: tvheadend
    app.kubernetes.io/component: server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.206
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/part-of: tvheadend
    app.kubernetes.io/name: tvheadend
    app.kubernetes.io/component: server
  ports:
    - name: webui
      port: 9981
      targetPort: webui
    - name: htsp
      port: 9982
      targetPort: htsp
