apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  labels: &labels
    app.kubernetes.io/part-of: changedetection
    app.kubernetes.io/name: changedetection
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  serviceName: "changedetection"
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: changedetection-data
      containers:
        - name: changedetection
          image: dgtlmoon/changedetection.io:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /datastore
          ports:
            - containerPort: 5000
              name: http
