apiVersion: v1
kind: Service
metadata:
  name: changedetection
  labels:
    app.kubernetes.io/instance: changedetection
    app.kubernetes.io/name: changedetection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: changedetection
    app.kubernetes.io/name: changedetection
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
