apiVersion: v1
kind: Service
metadata:
  name: espial
  labels:
    app.kubernetes.io/part-of: espial
    app.kubernetes.io/name: espial
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: espial
    app.kubernetes.io/name: espial
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 3000
      targetPort: http
