apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-secret
    namespace: networking
stringData:
    cloudflare_api_key: ENC[AES256_GCM,data:2V+F4U3QcBHtqV8IK5u4MQ42BJSgua0WFLPhp3JkZDsb+TEc9Q==,iv:MyET1Dt6owykDlQzakyYvdMdhWaHJ8Vp1mnQ8FIOCXk=,tag:Lnu5C/yBY30tgwlf96yHzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rywm2s9s24hma5q3rvnn3tl8ys5ccajwhyyv696j25secg43657suarrph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcmd6bVVPQnpmYjRqay9m
            TUR3VXpnV0t1Vjl3UEplbHErMWVKckFxd1FvCnlDeDJ5cEswM1N4K2VML0J4UGgy
            N0RPeDdJME5pbUFoSmRLd056YnUzb28KLS0tIDVJYTZDbXhXdUZxVktUTlJ5YjQw
            d0NXNzFEMjRjSGcxT3pJSUJ0SWpqbXMKfqpFq5SGw/jcNu15YBIC2OApeH25TdV5
            eEqSw+cAd1Eqwc6HOYfYUPy1V4eV1xQVt5/qFkRM+Lr5SVF6IEuzyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T02:43:08Z"
    mac: ENC[AES256_GCM,data:cL8FFExXI5ZpPtgSCIosotCr6GibkDIUkNYcFMH6mwqNfBY37dVOIHJegT9J6dWuAaXYdzwWAkJFzpf2OZOOkutdwgVeab6Qm/y5ThzD2n/OmS1XTlOfFToPs9BBaF8N+Rh1njxcwJ3pYhSI3JQj0eCHGmzFIlRvVxTY3UJB0BI=,iv:jJBUItWECDUpJobXFAkSOhdQrJp3xhVFmGyUb72XFbw=,tag:Q64z+2OQKZg2GINLtMzSNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
