apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels: &labels
    app.kubernetes.io/part-of: sonarr
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/component: server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  serviceName: "sonarr"
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: share
          hostPath:
            path: /mnt/storage
            type: Directory
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8989
              name: http
          env:
            - name: TZ
              value: Asia/Jakarta
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: share
              mountPath: /share
