apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/part-of: sonarr
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: sonarr
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/component: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
