---
apiVersion: v1
kind: Service
metadata:
  name: szurubooru-web
  labels:
    app.kubernetes.io/part-of: szurubooru
    app.kubernetes.io/name: szurubooru-web
    app.kubernetes.io/component: web
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/part-of: szurubooru
    app.kubernetes.io/name: szurubooru-web
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
