apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  labels:
    labels: &labels
      app.kubernetes.io/part-of: memos
      app.kubernetes.io/name: memos
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: memos-data
      containers:
        - name: memos
          image: ghcr.io/usememos/memos:0.17.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5230
              name: http
          env:
            - name: MEMOS_PORT
              value: "5230"
          volumeMounts:
            - name: data
              mountPath: /var/opt/memos
