apiVersion: v1
kind: Service
metadata:
  name: memos
  labels:
    app.kubernetes.io/part-of: memos
    app.kubernetes.io/name: memos
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: memos
    app.kubernetes.io/name: memos
  ports:
    - name: http
      port: 5230
      targetPort: http
