---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: '0.9.2'
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  values: {}
