---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: external-dns-cloudflare-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: cloudflare_api_token
          remoteRef:
              key: Cloudflare
              property: token
