apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "transmission"
    metallb.universe.tf/loadBalancerIPs: 192.168.2.204
  labels:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
  ports:
    - protocol: TCP
      port: 51413
      targetPort: torrent-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "transmission"
    metallb.universe.tf/loadBalancerIPs: 192.168.2.204
  labels:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/name: transmission
  ports:
    - protocol: UDP
      port: 51413
      targetPort: torrent-udp
