apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app.kubernetes.io/part-of: radarr
    app.kubernetes.io/name: radarr
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: radarr
    app.kubernetes.io/name: radarr
    app.kubernetes.io/component: server
  ports:
    - name: http
      protocol: TCP
      port: 7878
      targetPort: http
