---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.5
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values: {}
