---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: espial-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: username
          remoteRef:
              key: Espial
              property: username
        - secretKey: password
          remoteRef:
              key: Espial
              property: password
