apiVersion: apps/v1
kind: Deployment
metadata:
  name: szurubooru-web
  labels: &labels
    app.kubernetes.io/part-of: szurubooru
    app.kubernetes.io/name: szurubooru-web
    app.kubernetes.io/component: web
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      volumes:
        - name: share
          hostPath:
            path: /mnt/storage/apps/szurubooru
            type: Directory
      containers:
        - name: szurubooru-web
          image: szurubooru/client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: BACKEND_HOST
              value: szurubooru-backend
            - name: BASE_URL
              value: https://szurubooru.fadhlika.com
          volumeMounts:
            - name: share
              mountPath: /data
