---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: github-config-secret
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword
    data:
        - secretKey: github_token
          remoteRef:
              key: Github
              property: actions-runner-controller
