---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnels-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnels-operator
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: cloudflare-tunnels-operator
        namespace: flux-system
  values: {}
