apiVersion: apps/v1
kind: Deployment
metadata:
  name: szurubooru-backend
  labels:
    app.kubernetes.io/name: szurubooru-backend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: szurubooru-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: szurubooru-backend
    spec:
      restartPolicy: Always
      volumes:
        - name: secret
          secret:
            secretName: szurubooru-secret
        - name: share
          nfs:
            server: openmediavault.oyoy.lan
            path: /storage/apps/szurubooru
      containers:
        - name: backend
          image: szurubooru/server:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: szurubooru-postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: szurubooru-postgres-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: szurubooru-postgres-secret
                  key: db_password
          ports:
            - containerPort: 6666
              name: http
          volumeMounts:
            - name: secret
              mountPath: /opt/app/config.yaml
              subPath: config.yaml
            - name: share
              mountPath: /data
