---
apiVersion: v1
kind: Service
metadata:
  name: szurubooru-backend
  labels:
    app.kubernetes.io/name: szurubooru-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: szurubooru-backend
  ports:
    - name: http
      port: 6666
      targetPort: http
